In [7]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [22]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')

In [32]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, -1].values

In [33]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [34]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [35]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [36]:
# Encoding categorical Data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()

In [37]:
X[:, 1] = labelencoder.fit_transform(X[:, 1])
X[:, 2] = labelencoder.fit_transform(X[:, 2])

In [38]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [39]:
onehot = OneHotEncoder(categorical_features=[1])
X = onehot.fit_transform(X).toarray()

/home/phoenix/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [42]:
X.shape

(10000, 12)

In [43]:
 # avoiding dummy variable trap
X = X[:, 1:]

In [44]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [45]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [46]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [49]:
# Fitting classifier to the Training set
# Create your classifier here
import keras
from keras.models import Sequential
from keras.layers import Dense # to create the ann

In [51]:
# initialize the neural network
classifier = Sequential()

In [60]:
# Adding input layers and hidden layers
classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu', input_dim = 11))

In [62]:
# adding second hidden layers
classifier.add(Dense(units=6,
                     kernel_initializer='uniform',
                     activation='relu'))

In [63]:
# ouput layer
classifier.add(Dense(units=1,
                     kernel_initializer='uniform',
                     activation='sigmoid'))

In [64]:
# compiling the ann - gradient descent
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [65]:
# fit ann to training set
classifier.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
8000/8000 [==============================] - 3s 389us/step - loss: 0.5066 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 2s 230us/step - loss: 0.4319 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 247us/step - loss: 0.4243 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 2s 235us/step - loss: 0.4192 - acc: 0.8102
Epoch 5/100
8000/8000 [==============================] - 2s 240us/step - loss: 0.4166 - acc: 0.8270
Epoch 6/100
8000/8000 [==============================] - 2s 247us/step - loss: 0.4146 - acc: 0.8294
Epoch 7/100
8000/8000 [==============================] - 2s 240us/step - loss: 0.4128 - acc: 0.8290
Epoch 8/100
8000/8000 [==============================] - 2s 269us/step - loss: 0.4118 - acc: 0.8321
Epoch 9/100
8000/8000 [==============================] - 2s 262us/step - loss: 0.4107 - acc: 0.8340
Epoch 10/100
8000/8000 [==============================] - 2s 247us/step - loss: 0.4096 - acc: 0.8341

8000/8000 [==============================] - 2s 252us/step - loss: 0.3999 - acc: 0.8344
Epoch 82/100
8000/8000 [==============================] - 2s 253us/step - loss: 0.4000 - acc: 0.8372
Epoch 83/100
8000/8000 [==============================] - 2s 239us/step - loss: 0.3999 - acc: 0.8352
Epoch 84/100
8000/8000 [==============================] - 2s 253us/step - loss: 0.3998 - acc: 0.8351
Epoch 85/100
8000/8000 [==============================] - 2s 267us/step - loss: 0.3997 - acc: 0.8357
Epoch 86/100
8000/8000 [==============================] - 2s 261us/step - loss: 0.3994 - acc: 0.8350
Epoch 87/100
8000/8000 [==============================] - 2s 262us/step - loss: 0.3996 - acc: 0.8360
Epoch 88/100
8000/8000 [==============================] - 2s 272us/step - loss: 0.4002 - acc: 0.8345
Epoch 89/100
8000/8000 [==============================] - 2s 272us/step - loss: 0.3999 - acc: 0.8356
Epoch 90/100
8000/8000 [==============================] - 2s 265us/step - loss: 0.4000 - acc: 0.8351
Epo

In [87]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [88]:
y_pred = (y_pred > 0.5)

In [89]:
y_test.shape

(2000,)

In [91]:
y_pred.shape

(2000, 1)

In [93]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred); print(cm)

[[1540   55]
 [ 267  138]]


In [94]:
(1540 + 138)/2000

0.839